theme: jekyll-theme-cayman

# Edits based on github docs here: remote_theme: tuur29/pages-themes-cayman
remote_theme: tuur29/pages-themes-cayman

# Title & description
title: [Omodayo Origunwa]
description: [Welcome to my website!]

# Usage monitoring
google_analytics: [G-DTHLMSW9SX]
